---
dist: bionic
language: bash
sudo: required

before_install:
  - sudo apt-get install --yes shellcheck yamllint pylint3
  - misc/scripts/lint_project.py
  - curl https://raw.githubusercontent.com/express42/otus-platform-tests/2019-12/run.sh | bash  # yamllint disable-line rule:line-length
