---

prometheus:
  additionalServiceMonitors:
    - name: nginx
      selector:
        matchLabels:
          app: nginx
      namespaceSelector:
        any: true
      endpoints:
        - path: /metrics
          port: "metrics"
