---

global:
  tlsDisable: false

server:
  standalone:
    enabled: false
  extraEnvironmentVars:
    VAULT_CACERT: /vault/userconfig/vault-transit-server-tls/vault.ca

  ha:
    enabled: true
    # yamllint disable
    config: |
      disable_mlock = true
      ui = true
      cluster_addr = "https://POD_IP:8201"

      listener "tcp" {
        tls_disable = 0
        address = "[::]:8200"
        cluster_address = "[::]:8201"
        tls_cert_file = "/vault/userconfig/vault-transit-server-tls/vault.crt"
        tls_key_file  = "/vault/userconfig/vault-transit-server-tls/vault.key"
        tls_client_ca_file = "/vault/userconfig/vault-transit-server-tls/vault.ca"
      }
      storage "consul" {
        path = "vault-transit"
        address = "HOST_IP:8500"
      }
    # yamllint enable
  ui:
    enabled: true
    serviceType: "ClusterIP"

  extraVolumes:
    - type: secret
      name: vault-transit-server-tls
