---

values:
  - namespaces:
      - nginx-ingress
      - cert-manager
      - harbor

repositories:
  # helmfile uses stable https://kubernetes-charts.storage.googleapis.com
  # by default
  - name: stable
    url: https://kubernetes-charts.storage.googleapis.com
  - name: incubator
    url: https://kubernetes-charts-incubator.storage.googleapis.com
  - name: jetstack
    url: https://charts.jetstack.io
  - name: harbor
    url: https://helm.goharbor.io

templates:
  default: &default
    wait: true
    timeout: 240
    # atomic: true
    namespace: "{{`{{ .Release.Name }}`}}"
    values:
      - config/{{`{{ .Release.Name }}`}}/values.yaml
  raw: &raw
    chart: incubator/raw
    wait: true
    timeout: 120
    values:
      - config/{{`{{ .Release.Name }}`}}/values.yaml

releases:
  # Currently helm3 can't create namespaces
  # https://github.com/roboll/helmfile/issues/891
  - name: namespaces
    chart: incubator/raw
    namespace: default
    values:
      - resources:
{{ range $key := $.Values.namespaces }}
          - apiVersion: v1
            kind: Namespace
            metadata:
              name: {{ . }}
            spec:
{{ end }}


  - name: nginx-ingress
    <<: *default
    chart: stable/nginx-ingress
    version: 1.11.1
    needs:
      - default/namespaces


  - name: cert-manager
    <<: *default
    chart: jetstack/cert-manager
    version: 0.9.0
    hooks:
      - events: ["presync"]
        command: "kubectl"
        args: ["label", "--overwrite", "namespace", "cert-manager", "certmanager.k8s.io/disable-validation=true"]
      - events: ["presync"]
        command: "kubectl"
        args: ["apply", "-f", "https://raw.githubusercontent.com/jetstack/cert-manager/release-0.9/deploy/manifests/00-crds.yaml"]
    needs:
      - default/namespaces
      - nginx-ingress/nginx-ingress


  - name: cluster-issuer
    <<: *raw
    namespace: default
    needs:
      - default/namespaces
      - cert-manager/cert-manager
      - nginx-ingress/nginx-ingress


  - name: harbor
    <<: *default
    chart: harbor/harbor
    version: 1.1.2
    needs:
      - default/namespaces
      - cert-manager/cert-manager
      - nginx-ingress/nginx-ingress
      - default/cluster-issuer

