---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cartservice
spec:
  selector:
    matchLabels:
      app: cartservice-prod
  template:
    metadata:
      labels:
        app: cartservice-prod
