---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: prod-
bases:
  - ../../base
patchesStrategicMerge:
  - deployment.yaml
  - service.yaml
resources:
  - namespace.yaml
namespace: hipster-shop-prod
