---

backend:
  type: es
  es:
    host: elasticsearch-master
rawConfig: |
  @INCLUDE fluent-bit-service.conf
  @INCLUDE fluent-bit-input.conf
  @INCLUDE fluent-bit-filter.conf
  @INCLUDE fluent-bit-output.conf

  [FILTER]
    Name    modify
    Match   *
    Remove  time
    Remove  @timestamp


tolerations:
  - key: node-role
    operator: Exists
    effect: NoSchedule


# (*) collect logs from virtual machines
input:
  systemd:
    enabled: true
    stripUnderscores: true
    # setup an empty filter here to collect all systemd logs
    filters:
      systemdUnit: []

audit:
  enable: true
  input:
    memBufLimit: 35MB
    parser: json
    tag: audit.*
    path: /opt/rke/var/log/kube-audit/audit-log.json
    bufferChunkSize: 2MB
    bufferMaxSize: 10MB
    key: kubernetes-audit

extraVolumes:
  - name: auditlog
    hostPath:
      path: /opt/rke/var/log/kube-audit
      type: ""

extraVolumeMounts:
  - name: auditlog
    mountPath: /opt/rke/var/log/kube-audit
